remote_theme: pmarsceill/just-the-docs

title: SaaSBox Documentation
Description: Documentation for SaaSBox
ga_tracking: UA-128178901-2

permalink: pretty

search_enabled: true
plugins:
  - jekyll-seo-tag
